name: kube-state-metrics:2.0

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'google/kube-state-metrics/2.0/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:google/kube-state-metrics/2.0"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: rovast/kube-state-metrics:2.0

      - name: checkout code
        uses: actions/checkout@v2
      - name: Update dockerhub doc
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: rovast/kube-state-metrics
          short-description: https://github.com/rovast/docker-autobuild
          readme-filepath: ./README.md
