name: yapi

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'yapi/Dockerfile'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up docker-buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: 4.2.0-7
      - name: build & publish
        run: |
          docker login \
            --username ${{ secrets.DOCKERHUB_USERNAME }} \
            --password ${{ secrets.DOCKERHUB_TOKEN }}
          docker buildx build \
            -f ./yapi/Dockerfile \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --push \
            --tag rovast/yapi:latest .
  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: "{{defaultContext}}:yapi"
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: rovast/yapi

  #     - name: checkout code
  #       uses: actions/checkout@v2
  #     - name: Update dockerhub doc
  #       uses: peter-evans/dockerhub-description@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #         repository: rovast/docker-autobuild
  #         short-description: https://github.com/rovast/docker-autobuild
  #         readme-filepath: ./README.md
